2022-07-21 18:05:32  [ Canceler for Source: Custom Source (1/1)#0 (cf6f0115477400afba2d96eacc33cb50).:23597 ] - [ ERROR ]  Error while canceling the task Source: Custom Source (1/1)#0.
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2373)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2256)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2211)
	at org.why.source.KafkaSource.cancel(KafkaSource.java:63)
	at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:160)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:210)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:191)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.cancel(StreamTask.java:762)
	at org.apache.flink.runtime.taskmanager.Task$TaskCanceler.run(Task.java:1575)
	at java.lang.Thread.run(Thread.java:748)
2022-07-21 18:05:32  [ Legacy Source Thread - Source: Custom Source (1/1)#0:23597 ] - [ ERROR ]  kafka exception ：org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
2022-07-21 18:05:32  [ Canceler for Source: Custom Source (1/1)#0 (c8ef713df2348d87aaa45e11bd1718e2).:23601 ] - [ ERROR ]  Error while canceling the task Source: Custom Source (1/1)#0.
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2373)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2256)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2211)
	at org.why.source.KafkaSource.cancel(KafkaSource.java:63)
	at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:160)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:210)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:191)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.cancel(StreamTask.java:762)
	at org.apache.flink.runtime.taskmanager.Task$TaskCanceler.run(Task.java:1575)
	at java.lang.Thread.run(Thread.java:748)
2022-07-21 18:05:32  [ Legacy Source Thread - Source: Custom Source (1/1)#0:23601 ] - [ ERROR ]  kafka exception ：org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
2022-07-21 18:28:13  [ Canceler for Source: Custom Source (1/1)#0 (a39cf17ddc462334022fc5ca0284d8ca).:189896 ] - [ ERROR ]  Error while canceling the task Source: Custom Source (1/1)#0.
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2373)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2256)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2211)
	at org.why.source.KafkaSource.cancel(KafkaSource.java:63)
	at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:160)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:210)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:191)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.cancel(StreamTask.java:762)
	at org.apache.flink.runtime.taskmanager.Task$TaskCanceler.run(Task.java:1575)
	at java.lang.Thread.run(Thread.java:748)
2022-07-21 18:28:13  [ Legacy Source Thread - Source: Custom Source (1/1)#0:189912 ] - [ ERROR ]  kafka exception ：org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
2022-07-21 18:28:13  [ Canceler for Source: Custom Source (1/1)#0 (21346a2b7487ec0d2883465ef8997616).:189911 ] - [ ERROR ]  Error while canceling the task Source: Custom Source (1/1)#0.
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2373)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2256)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2211)
	at org.why.source.KafkaSource.cancel(KafkaSource.java:63)
	at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:160)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:210)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:191)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.cancel(StreamTask.java:762)
	at org.apache.flink.runtime.taskmanager.Task$TaskCanceler.run(Task.java:1575)
	at java.lang.Thread.run(Thread.java:748)
2022-07-21 18:28:13  [ Legacy Source Thread - Source: Custom Source (1/1)#0:189909 ] - [ ERROR ]  kafka exception ：org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
2022-07-21 19:09:17  [ Legacy Source Thread - Source: Custom Source (1/1)#0:15517 ] - [ ERROR ]  kafka exception ：org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
2022-07-21 19:09:17  [ Canceler for Source: Custom Source (1/1)#0 (4b5662c245c1eaee465fb01bfc833bf7).:15517 ] - [ ERROR ]  Error while canceling the task Source: Custom Source (1/1)#0.
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2373)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2256)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2211)
	at org.why.source.KafkaSource.cancel(KafkaSource.java:63)
	at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:160)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:210)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:191)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.cancel(StreamTask.java:762)
	at org.apache.flink.runtime.taskmanager.Task$TaskCanceler.run(Task.java:1575)
	at java.lang.Thread.run(Thread.java:748)
2022-07-21 19:45:29  [ Canceler for Source: Custom Source (1/1)#0 (f09f9fde43742774d52c2bac107d4460).:14168 ] - [ ERROR ]  Error while canceling the task Source: Custom Source (1/1)#0.
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2373)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2256)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2211)
	at org.why.source.KafkaSource.cancel(KafkaSource.java:63)
	at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:160)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:210)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:191)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.cancel(StreamTask.java:762)
	at org.apache.flink.runtime.taskmanager.Task$TaskCanceler.run(Task.java:1575)
	at java.lang.Thread.run(Thread.java:748)
2022-07-21 19:45:29  [ Legacy Source Thread - Source: Custom Source (1/1)#0:14168 ] - [ ERROR ]  kafka exception ：org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
